Repository haykbit/react-music-player, pull requests merged in 2021-10, with the labels that each got.

#45 F16/my songs
  .gitignore
  client/.gitignore
  server/.gitignore
  server/src/controllers/index.js
  server/src/controllers/songController.js
  server/src/controllers/userController.js
  server/src/db/seed.js
  server/src/models/index.js
  server/src/models/songModel.js
  server/src/routes/index.js
  server/src/routes/songRoutes.js
  server/src/routes/userRoutes.js
  server/src/server.js
Labels: must-have, user-story

#47 F12: songs upload
  client/src/App.js
  client/src/Utils/constants.js
  client/src/api/api.js
  client/src/components/ProfileInfo/ProfileInfo.js
  client/src/components/ProfileInfo/styles/profileInfo.css
  client/src/components/ProfileInfo/styles/profileInfo.css.map
  client/src/components/ProfileInfo/styles/profileInfo.scss
  client/src/components/RegisterForm/FormSchema.js
  client/src/components/UploadInfo/UploadInfo.js
  client/src/components/UserProfile/UserProfile.js
  client/src/components/testUserProfile/testUserProfile.js
  client/src/redux/auth/action.js
  client/src/redux/reducers.js
  client/src/redux/song/action.js
  client/src/redux/song/reducer.js
  client/src/redux/song/state.js
  client/src/redux/song/types.js
  client/src/redux/user/action.js
  client/src/services/auth/auth.js
  client/src/services/cloudinary/cloudinary.js
  client/src/services/cloudinary/index.js
  server/src/controllers/songController.js
  server/src/controllers/userController.js
  server/src/index.js
  server/src/models/songModel.js
  server/src/models/userModel.js
  server/src/routes/songRoutes.js
Labels: feat, must-have, user-story

#59 Fix46: auth observer
  client/src/App.js
  client/src/components/ProfileInfo/ProfileInfo.js
  client/src/pages/Login/Login.js
  client/src/redux/auth/action.js
  client/src/redux/auth/reducer.js
  client/src/redux/auth/state.js
  client/src/redux/auth/types.js
  client/src/services/auth/auth.js
  server/src/controllers/songController.js
  server/src/db/seed.js
  server/src/routes/songRoutes.js
Labels: bug

#62 F16/my songs visualization
  client/src/App.js
  client/src/assets/images/icons/upload-icon.png
  client/src/components/IndivualSong/IndividualSong.js
  client/src/components/IndivualSong/index.js
  client/src/components/Modal/Modal.js
  client/src/components/Modal/index.js
  client/src/components/Modal/style/modal.scss
  client/src/components/MyPlaylist/Myplaylist.js
  client/src/components/MyPlaylist/index.js
  client/src/components/MyPlaylist/style/myPlaylist.scss
  client/src/components/Navbar/Navbar.js
  client/src/components/PlaylistNew/PlaylistNew.js
  client/src/components/PlaylistStack/PlaylistStack.js
  client/src/components/PlaylistStack/index.js
  client/src/components/PlaylistStack/style/playlistStack.scss
  client/src/components/RightClickMenu/RightClickMenu.js
  client/src/components/RightClickMenu/index.js
  client/src/components/RightClickMenu/style/rightClickMenu.scss
  client/src/hooks/index.js
  client/src/hooks/useRightClickMenu.js
  client/src/pages/Playlists/Playlists.js
  client/src/pages/Playlists/index.js
  client/src/pages/Playlists/style/playlist.scss
Labels: feat, must-have, user-story

#63 F17: like songs
  client/src/App.js
  client/src/api/api.js
  client/src/components/IndividualSong/IndividualSong.js
  client/src/components/IndividualSong/index.js
  client/src/components/Modal/FormSchema.js
  client/src/components/Modal/Modal.js
  client/src/components/Modal/style/modal.scss
  client/src/components/MyPlaylist/style/myPlaylist.scss
  client/src/components/Navbar/Navbar.js
  client/src/components/Navbar/style/navbar.css
  client/src/components/Navbar/style/navbar.css.map
  client/src/components/Navbar/style/navbar.scss
  client/src/components/PlaylistStack/PlaylistStack.js
  client/src/components/PlaylistStack/style/playlistStack.css
  client/src/components/PlaylistStack/style/playlistStack.css.map
  client/src/components/PlaylistStack/style/playlistStack.scss
  client/src/components/ProfileInfo/ProfileInfo.js
  client/src/components/UploadInfo/UploadInfo.js
  client/src/pages/Login/Login.js
  client/src/redux/auth/action.js
  client/src/redux/auth/reducer.js
  client/src/redux/playList/action.js
  client/src/redux/playList/reducer.js
  client/src/redux/playList/state.js
  client/src/redux/playList/types.js
  client/src/redux/song/action.js
  client/src/redux/song/reducer.js
  client/src/redux/song/state.js
  client/src/redux/song/types.js
  client/src/redux/user/action.js
  server/src/controllers/songController.js
  server/src/controllers/userController.js
  server/src/models/songModel.js
  server/src/models/userModel.js
  server/src/routes/songRoutes.js
  server/src/routes/userRoutes.js
Labels: feat, must-have, user-story

#70 F54/playlist creation
  client/src/App.js
  client/src/api/api.js
  client/src/components/IndividualSong/IndividualSong.js
  client/src/components/MyPlaylist/index.js
  client/src/components/ProfileInfo/ProfileInfo.js
  client/src/redux/playList/action.js
  client/src/redux/playList/reducer.js
  client/src/redux/playList/state.js
  client/src/redux/reducers.js
  server/src/controllers/playlistController.js
  server/src/index.js
  server/src/models/playlistModel.js
  server/src/models/songModel.js
  server/src/models/userModel.js
Labels: bug, feat, must-have, user-story

#71 F55/playlist view
  client/src/App.js
  client/src/components/IndividualSong/IndividualSong.js
  client/src/components/Playlist/Playlist.js
  client/src/components/Playlist/style/playlistcomponent.css
  client/src/components/Playlist/style/playlistcomponent.css.map
  client/src/components/PlaylistStack/PlaylistStack.js
  client/src/components/PlaylistStack/style/playlistStack.css
  client/src/components/PlaylistStack/style/playlistStack.css.map
  client/src/components/PlaylistStack/style/playlistStack.scss
  server/.gitignore
Labels: feat

#72 Fix/navbar playlist links
  client/src/components/Navbar/Navbar.js
Labels: enhancement

#74 F25: playlist player
  client/src/App.js
  client/src/api/api.js
  client/src/components/IndividualSong/IndividualSong.js
  client/src/components/Navbar/Navbar.js
  client/src/components/Playlist/Playlist.js
  client/src/components/PlaylistStack/PlaylistStack.js
  client/src/components/PlaylistStack/style/playlistStack.css
  client/src/components/PlaylistStack/style/playlistStack.css.map
  client/src/components/PlaylistStack/style/playlistStack.scss
  client/src/components/SongBar/AudioPlayer.js
  client/src/pages/IndividualPlaylist/IndividualPlaylist.js
  client/src/pages/IndividualPlaylist/index.js
  client/src/pages/IndividualPlaylist/style/playlist.css
  client/src/pages/IndividualPlaylist/style/playlist.css.map
  client/src/pages/IndividualPlaylist/style/playlist.scss
  client/src/redux/player/action.js
  client/src/redux/player/reducer.js
  client/src/redux/player/state.js
  client/src/redux/player/types.js
  client/src/redux/reducers.js
Labels: bug, feat, must-have, user-story

#82 F54/playlist creation
  client/src/App.js
  client/src/api/api.js
  client/src/components/CreatePlaylistModal/CreatePlaylistModal.js
  client/src/components/CreatePlaylistModal/FormSchema.js
  client/src/components/CreatePlaylistModal/index.js
  client/src/components/CreatePlaylistModal/style/createPlaylistModal.css
  client/src/components/CreatePlaylistModal/style/createPlaylistModal.css.map
  client/src/components/CreatePlaylistModal/style/createPlaylistModal.scss
  client/src/components/IndividualSong/IndividualSong.js
  client/src/components/Input/Textarea/Textarea.js
  client/src/components/Input/Textarea/index.js
  client/src/components/Input/Textarea/style/textarea.css
  client/src/components/Input/Textarea/style/textarea.css.map
  client/src/components/Input/Textarea/style/textarea.scss
  client/src/components/Playlist/Playlist.js
  client/src/components/Playlist/style/playlistcomponent.css
  client/src/components/Playlist/style/playlistcomponent.css.map
  client/src/components/PlaylistGrid/PlaylistGrid.js
  client/src/components/PlaylistGrid/style/playlistgrid.css
  client/src/components/PlaylistGrid/style/playlistgrid.css.map
  client/src/components/PlaylistGrid/style/playlistgrid.scss
  client/src/components/PlaylistStack/PlaylistStack.js
  client/src/pages/Home/Home.js
  client/src/pages/Profile/Profile.js
  client/src/redux/playList/action.js
  client/src/redux/playList/reducer.js
  client/src/redux/playList/state.js
  client/src/redux/playList/types.js
  client/src/redux/player/action.js
  server/src/controllers/playlistController.js
  server/src/controllers/songController.js
  server/src/models/playlistModel.js
  server/src/models/songModel.js
  server/src/routes/playlistRoutes.js
  server/src/routes/songRoutes.js
Labels: bug, feat, must-have, user-story

#91 Fix/changing image in modal
  client/src/components/CreatePlaylistModal/CreatePlaylistModal.js
  client/src/components/Modal/Modal.js
Labels: enhancement

#111 F80/user view
  client/src/components/PlaylistUser/PlaylistUser.js
  client/src/components/PlaylistUser/style/playlistuser.scss
Labels: enhancement

#115 F79/most played genre
  client/package.json
  client/src/App.js
  client/src/api/stats-api.js
  client/src/components/AddToPlaylist/AddToPlaylist.js
  client/src/components/AddToPlaylist/style/addToPlaylist.scss
  client/src/components/LoginForm/LoginForm.js
  client/src/components/LoginForm/style/loginform.scss
  client/src/components/PlaylistUser/style/playlistuser.scss
  client/src/components/UploadedSongsPlaylist/SongEditModal/FormSchema.js
  client/src/components/UploadedSongsPlaylist/SongEditModal/SongEditModal.js
  client/src/redux/auth/action.js
  client/src/redux/playList/action.js
  client/src/redux/player/action.js
  client/src/redux/song/action.js
  client/src/redux/user/action.js
  server/src/controllers/songController.js
Labels: enhancement, feat, user-story

#123 General styling
  client/src/App.js
  client/src/components/PlaylistGrid/PlaylistGrid.js
  client/src/components/PlaylistGrid/style/playlistgrid.scss
  client/src/components/PlaylistUser/PlaylistUser.js
  client/src/components/PlaylistUser/style/playlistuser.scss
  client/src/components/UserProfile/UserProfile.js
  client/src/components/UserProfile/style/userprofile.scss
Labels: enhancement

#124 General styling
  client/src/components/Modal/style/modal.scss
  client/src/components/Playlist/PlaylistStack/style/playliststack.css
  client/src/components/Playlist/PlaylistStack/style/playliststack.css.map
  client/src/components/Playlist/PlaylistStack/style/playliststack.scss
  client/src/components/Playlist/style/playlistcomponent.scss
  client/src/components/PlaylistGrid/PlaylistGrid.js
Labels: enhancement

#130 Fix/url to home
  client/src/components/Navbar/Navbar.js
Labels: bug

#131 style: general style
  client/src/assets/images/icons/logo-oasis.png
  client/src/components/LoginForm/LoginForm.js
  client/src/components/LoginForm/style/loginform.scss
  client/src/components/Navbar/Navbar.js
  client/src/components/Playlist/style/playlistcomponent.scss
  client/src/components/UserProfile/style/userprofile.scss
Labels: feat
