Repository haykbit/react-music-player, pull requests merged in 2021-09, with the labels that each got.

#14 feat: created monorepo structure / created react app
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  gitignore.git
  node_modules/.yarn-integrity
  node_modules/workspaces/LICENSE
  node_modules/workspaces/README.md
  node_modules/workspaces/dist/bootstrap.js
  node_modules/workspaces/dist/bootstrap.js.map
  node_modules/workspaces/dist/workspace.js
  node_modules/workspaces/dist/workspace.js.map
  node_modules/workspaces/dist/workspace.mjs
  node_modules/workspaces/dist/workspace.mjs.map
  node_modules/workspaces/package.json
  node_modules/workspaces/src/cli.coffee
  node_modules/workspaces/src/index.coffee
  package.json
  yarn.lock
Labels: feat

#15 feat: monorepo and dependencies structure
  .gitignore
  client/package.json
  node_modules/.yarn-integrity
  node_modules/workspaces/LICENSE
  node_modules/workspaces/README.md
  node_modules/workspaces/dist/bootstrap.js
  node_modules/workspaces/dist/bootstrap.js.map
  node_modules/workspaces/dist/workspace.js
  node_modules/workspaces/dist/workspace.js.map
  node_modules/workspaces/dist/workspace.mjs
  node_modules/workspaces/dist/workspace.mjs.map
  node_modules/workspaces/package.json
  node_modules/workspaces/src/index.coffee
  package.json
  server/package.json
  server/src/config/toremove.txt
  server/src/controllers/toremove.txt
  server/src/db/toremove.txt
  server/src/index.js
  server/src/middleware/toremove.txt
  server/src/models/toremove.txt
  server/src/routes/toremove.txt
  server/src/server.js
  yarn.lock
Labels: feat

#28 F03/user register
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/Utils/constants.js
  client/src/assets/images/pexels-elevate-1267350 (1).jpg
  client/src/assets/images/portada-1.png
  client/src/assets/images/portada-2.png
  client/src/assets/images/portada-3.png
  client/src/assets/images/portada-4.png
  client/src/assets/images/profile.jpg
  client/src/components/Navbar/Navbar.js
  client/src/components/Navbar/index.js
  client/src/components/Navbar/style/navbar.css
  client/src/components/Navbar/style/navbar.css.map
  client/src/components/Navbar/style/navbar.scss
  client/src/components/RegisterForm/RegisterForm.css
  client/src/components/RegisterForm/RegisterForm.css.map
  client/src/components/RegisterForm/RegisterForm.js
  client/src/components/RegisterForm/RegisterForm.scss
  client/src/components/RegisterForm/index.js
  client/src/components/RegisterForm/style/RegisterForm.css
  client/src/components/RegisterForm/style/RegisterForm.css.map
  client/src/components/RegisterForm/style/RegisterForm.scss
  client/src/logo.svg
  client/src/pages/Register/Register.js
  client/src/pages/Register/index.js
  client/src/pages/Register/styles/register.css
  client/src/pages/Register/styles/register.css.map
  client/src/pages/Register/styles/register.scss
  node_modules/.yarn-integrity
  package-lock.json
Labels: feat

#31 F01/user authentication
  client/package-lock.json
  client/src/api/api.js
  client/src/components/LoginForm/LoginForm.js
  client/src/components/LoginForm/style/loginform.css
  client/src/components/LoginForm/style/loginform.css.map
  client/src/components/LoginForm/style/loginform.scss
  client/src/components/RegisterForm/RegisterForm.js
  client/src/components/RegisterForm/style/RegisterForm.css
  client/src/components/RegisterForm/style/RegisterForm.css.map
  client/src/pages/Home/style/home.css
  client/src/pages/Home/style/home.css.map
  client/src/pages/Register/styles/register.css
  client/src/pages/Register/styles/register.css.map
  client/src/redux/auth/action.js
  server/node_modules/.bin/nodemon
  server/src/config/config.env
  server/src/config/firebaseConfig.env
  server/src/controllers/userController.js
  server/src/db/seed.js
  server/src/index.js
  yarn.lock
Labels: enhancement, feat, user-story

#33 F02/user logout
  client/src/App.js
  client/src/api/api.js
  client/src/components/AlbumExplorer/style/albumexplorer.scss
  client/src/components/LoginForm/LoginForm.js
  client/src/components/LoginForm/style/loginform.css
  client/src/components/LoginForm/style/loginform.css.map
  client/src/components/LoginForm/style/loginform.scss
  client/src/components/Navbar/Navbar.js
  client/src/components/Navbar/style/navbar.scss
  client/src/components/PasswordRecovery/PasswordRecovery.js
  client/src/components/PasswordRecovery/RecoverySchema.js
  client/src/components/PasswordRecovery/index.js
  client/src/components/PasswordRecovery/style/passwordRecovery.scss
  client/src/components/PlaylistCarrusel/style/playlist.scss
  client/src/components/PlaylistNew/style/playlistnew.scss
  client/src/components/RegisterForm/RegisterForm.js
  client/src/components/UserProfile/UserProfile.js
  client/src/components/UserProfile/index.js
  client/src/components/UserProfile/style/userprofile.scss
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/index.js
  client/src/pages/Profile/style/profile.scss
  client/src/pages/Recover/Recover.js
  client/src/redux/auth/action.js
  client/src/redux/auth/reducer.js
  client/src/redux/auth/state.js
  client/src/redux/auth/types.js
  server/src/controllers/userController.js
  server/src/db/seed.js
  server/src/routes/user.js
  server/src/routes/userRoutes.js
Labels: enhancement, feat, user-story

#34 F04: pass recovery
  client/src/components/LoginForm/LoginForm.js
  client/src/components/LoginForm/style/loginform.css
  client/src/components/LoginForm/style/loginform.css.map
  client/src/components/LoginForm/style/loginform.scss
  client/src/components/PasswordRecovery/PasswordRecovery.js
  client/src/components/PasswordRecovery/style/passwordRecovery.scss
Labels: feat, must-have, user-story

#36 F03/user register
  client/package.json
  client/src/App.js
  client/src/assets/images/albums/arctic-album-0.jpg
  client/src/assets/images/albums/arctic-album-1.jpeg
  client/src/assets/images/albums/arctic-album-2.jpeg
  client/src/assets/images/albums/arctic-album-3.jpeg
  client/src/assets/images/albums/arctic-album-4.jpg
  client/src/assets/images/albums/arctic-album-5.jpg
  client/src/assets/images/albums/coldplay-spies.jpeg
  client/src/assets/images/albums/gorillaz-demon-days.png
  client/src/assets/images/albums/linkin-p-papercut.jpeg
  client/src/assets/images/albums/oasis-morning.jpg
  client/src/assets/images/albums/the-killer-pressure.jpeg
  client/src/assets/images/albums/the-modern-age.jpeg
  client/src/assets/images/albums/twenty-op-hype.jpeg
  client/src/assets/images/icons/gmail.png
  client/src/assets/images/icons/pexels-elevate-1267350 (1).jpg
  client/src/assets/images/icons/pexels-koolshooters-7142993.jpg
  client/src/assets/images/icons/portada-1.png
  client/src/assets/images/icons/portada-2.png
  client/src/assets/images/icons/portada-3.png
  client/src/assets/images/icons/portada-4.png
  client/src/assets/images/icons/profile.jpg
  client/src/assets/images/icons/search.png
  client/src/components/AlbumExplorer/AlbumExplorer.js
  client/src/components/AlbumExplorer/style/albumexplorer.css
  client/src/components/AlbumExplorer/style/albumexplorer.css.map
  client/src/components/AlbumExplorer/style/albumexplorer.scss
  client/src/components/LoginForm/LoginForm.js
  client/src/components/Navbar/Navbar.js
  client/src/components/PlaylistCarrusel/PlaylistCarrusel.js
  client/src/components/PlaylistNew/PlaylistNew.js
  client/src/components/UserProfile/UserProfile.js
  client/src/pages/Login/styles/login.css
  client/src/pages/Login/styles/login.css.map
  client/src/pages/Login/styles/login.scss
  client/src/pages/Register/styles/register.css
  client/src/pages/Register/styles/register.css.map
  client/src/pages/Register/styles/register.scss
  server/.gitignore
Labels: feat

#37 F06: profile edit
  client/src/App.js
  client/src/api/api.js
  client/src/components/Input/Checkboxes/Checkbox.js
  client/src/components/Input/Checkboxes/index.js
  client/src/components/LoginForm/LoginForm.js
  client/src/components/Navbar/Navbar.js
  client/src/components/Navbar/style/navbar.css
  client/src/components/Navbar/style/navbar.css.map
  client/src/components/Navbar/style/navbar.scss
  client/src/components/PaymentInfo/PaymentInfo.js
  client/src/components/PaymentInfo/index.js
  client/src/components/PaymentInfo/style/paymentInfo.css
  client/src/components/PaymentInfo/style/paymentInfo.css.map
  client/src/components/PaymentInfo/style/paymentInfo.scss
  client/src/components/PlaylistCarrusel/style/playlist.css
  client/src/components/PlaylistNew/style/playlistnew.css
  client/src/components/ProfileInfo/ProfileInfo.js
  client/src/components/ProfileInfo/index.js
  client/src/components/ProfileInfo/styles/profileInfo.css
  client/src/components/ProfileInfo/styles/profileInfo.css.map
  client/src/components/ProfileInfo/styles/profileInfo.scss
  client/src/components/RegisterForm/RegisterForm.js
  client/src/components/RegisterForm/style/RegisterForm.css.map
  client/src/components/RegisterForm/style/RegisterForm.scss
  client/src/components/SubscriptionInfo/SubscriptionInfo.js
  client/src/components/SubscriptionInfo/index.js
  client/src/components/SubscriptionInfo/style/subscriptionInfo.css
  client/src/components/SubscriptionInfo/style/subscriptionInfo.css.map
  client/src/components/SubscriptionInfo/style/subscriptioninfo.scss
  client/src/components/UploadInfo/UploadInfo.js
  client/src/components/UploadInfo/index.js
  client/src/components/UploadInfo/style/uploadinfo.css
  client/src/components/UploadInfo/style/uploadinfo.css.map
  client/src/components/UploadInfo/style/uploadinfo.scss
  client/src/components/UserProfile/UserProfile.js
  client/src/components/UserProfile/style/userprofile.css
  client/src/components/UserProfile/style/userprofile.css.map
  client/src/components/UserProfile/style/userprofile.scss
  client/src/components/testUserProfile/testUserProfile.js
  client/src/pages/Profile/style/profile.css
  client/src/pages/Profile/style/profile.css.map
  client/src/pages/Recover/Recover.js
  client/src/redux/auth/action.js
  client/src/redux/reducers.js
  client/src/redux/user/action.js
  client/src/redux/user/reducer.js
  client/src/redux/user/state.js
  client/src/redux/user/types.js
  client/src/services/auth/auth.js
  client/src/services/auth/index.js
  server/src/controllers/userController.js
  server/src/db/seed.js
  server/src/routes/userRoutes.js
Labels: feat, user-story

#40 F06: profile edit
  client/src/assets/images/icons/closeIcon.png
  client/src/assets/images/icons/uploadImage.png
  client/src/components/Navbar/Navbar.js
  client/src/components/ProfileInfo/FormSchema.js
  client/src/components/ProfileInfo/ProfileInfo.js
  client/src/components/ProfileInfo/styles/profileInfo.scss
  client/src/redux/user/action.js
  client/src/redux/user/reducer.js
  client/src/redux/user/types.js
Labels: must-have, user-story
